# Generated by Django 4.1.6 on 2023-09-08 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_review_reviewername_reviewerphoto'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudioGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='studio/')),
            ],
        ),
    ]
