# Generated by Django 4.1.6 on 2023-09-11 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_banner_email_firstname_lastname_message_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='photos/')),
                ('name', models.CharField(max_length=250)),
                ('job', models.CharField(max_length=250)),
                ('text', models.TextField()),
                ('fb', models.URLField()),
                ('tw', models.URLField()),
                ('inst', models.URLField()),
                ('github', models.URLField()),
                ('linkedin', models.URLField()),
            ],
        ),
        migrations.DeleteModel(
            name='AboutVideo',
        ),
        migrations.DeleteModel(
            name='TeamName',
        ),
        migrations.DeleteModel(
            name='TeamPhoto',
        ),
        migrations.DeleteModel(
            name='TeamText',
        ),
        migrations.DeleteModel(
            name='TeamUrls',
        ),
        migrations.AddField(
            model_name='about',
            name='features',
            field=models.ManyToManyField(to='main.aboutfeatures'),
        ),
        migrations.AddField(
            model_name='about',
            name='video_url',
            field=models.URLField(default=5),
            preserve_default=False,
        ),
    ]
