# Generated by Django 4.1.6 on 2023-09-11 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_team_delete_aboutvideo_delete_teamname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='projects/')),
                ('is_left', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('url', models.URLField()),
                ('author_words', models.TextField()),
                ('author', models.CharField(max_length=250)),
                ('author_photo', models.ImageField(upload_to='authors/')),
            ],
        ),
        migrations.DeleteModel(
            name='AuthorPhoto',
        ),
        migrations.DeleteModel(
            name='AuthorWords',
        ),
        migrations.DeleteModel(
            name='ProjectAuthor',
        ),
        migrations.DeleteModel(
            name='ProjectName',
        ),
        migrations.DeleteModel(
            name='ProjectPhoto',
        ),
        migrations.DeleteModel(
            name='ProjectURL',
        ),
    ]
