# Generated by Django 4.1.6 on 2023-09-11 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_delete_email_delete_firstname_delete_lastname_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
