# Generated by Django 4.1.6 on 2023-09-11 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_delete_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.TextField()),
                ('fb', models.URLField()),
                ('tw', models.URLField()),
                ('inst', models.URLField()),
                ('linkedin', models.URLField()),
            ],
        ),
    ]
